<script>
    const dataCourseCards =  [
  {
    numberLessons: "01",
    courseName: "Introduction to Daily Life",
    numberNewWords: 8,
    numberLingQs: 9,
    numberKnownWords: 10,
    newWordsPercents: 12,
  },
  {
    numberLessons: "02",
    courseName: "Talking About Hobbies",
    numberNewWords: 12,
    numberLingQs: 7,
    numberKnownWords: 18,
    newWordsPercents: 15,
  },
  {
    numberLessons: "03",
    courseName: "Work and Studies",
    numberNewWords: 6,
    numberLingQs: 5,
    numberKnownWords: 22,
    newWordsPercents: 9,
  },
  {
    numberLessons: "04",
    courseName: "Daily Routine",
    numberNewWords: 10,
    numberLingQs: 11,
    numberKnownWords: 14,
    newWordsPercents: 18,
  },
  {
    numberLessons: "05",
    courseName: "Food and Cooking",
    numberNewWords: 14,
    numberLingQs: 10,
    numberKnownWords: 20,
    newWordsPercents: 21,
  },
  {
    numberLessons: "06",
    courseName: "Health and Exercise",
    numberNewWords: 9,
    numberLingQs: 8,
    numberKnownWords: 25,
    newWordsPercents: 11,
  },
  {
    numberLessons: "07",
    courseName: "Technology in Life",
    numberNewWords: 16,
    numberLingQs: 13,
    numberKnownWords: 30,
    newWordsPercents: 24,
  },
  {
    numberLessons: "08",
    courseName: "Travel Experiences",
    numberNewWords: 11,
    numberLingQs: 9,
    numberKnownWords: 28,
    newWordsPercents: 17,
  },
  {
    numberLessons: "09",
    courseName: "Culture and Traditions",
    numberNewWords: 13,
    numberLingQs: 12,
    numberKnownWords: 26,
    newWordsPercents: 19,
  },
  {
    numberLessons: "10",
    courseName: "Family and Relationships",
    numberNewWords: 7,
    numberLingQs: 6,
    numberKnownWords: 32,
    newWordsPercents: 8,
  },
  {
    numberLessons: "11",
    courseName: "Shopping and Money",
    numberNewWords: 15,
    numberLingQs: 14,
    numberKnownWords: 21,
    newWordsPercents: 23,
  },
  {
    numberLessons: "12",
    courseName: "Education Systems",
    numberNewWords: 9,
    numberLingQs: 7,
    numberKnownWords: 35,
    newWordsPercents: 10,
  },
  {
    numberLessons: "13",
    courseName: "Social Media",
    numberNewWords: 18,
    numberLingQs: 15,
    numberKnownWords: 27,
    newWordsPercents: 26,
  },
  {
    numberLessons: "14",
    courseName: "Environmental Issues",
    numberNewWords: 14,
    numberLingQs: 11,
    numberKnownWords: 29,
    newWordsPercents: 20,
  },
  {
    numberLessons: "15",
    courseName: "Technology at Work",
    numberNewWords: 10,
    numberLingQs: 8,
    numberKnownWords: 40,
    newWordsPercents: 12,
  },
  {
    numberLessons: "16",
    courseName: "Future Plans",
    numberNewWords: 12,
    numberLingQs: 10,
    numberKnownWords: 34,
    newWordsPercents: 16,
  },
  {
    numberLessons: "17",
    courseName: "Problem Solving",
    numberNewWords: 17,
    numberLingQs: 14,
    numberKnownWords: 31,
    newWordsPercents: 25,
  },
  {
    numberLessons: "18",
    courseName: "Leadership and Teamwork",
    numberNewWords: 13,
    numberLingQs: 11,
    numberKnownWords: 38,
    newWordsPercents: 18,
  },
  {
    numberLessons: "19",
    courseName: "Culture Shock",
    numberNewWords: 8,
    numberLingQs: 6,
    numberKnownWords: 42,
    newWordsPercents: 9,
  },
  {
    numberLessons: "20",
    courseName: "Review and Reflection",
    numberNewWords: 5,
    numberLingQs: 4,
    numberKnownWords: 50,
    newWordsPercents: 6,
  },
];
   
</script>